<?php

use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\oyw_salesforce\SalesforceFieldValues;

/**
 * Provides allowed values for Salesforce fields.
 *
 * @param \Drupal\Core\Field\FieldStorageDefinitionInterface $definition
 *   The field storage definition.
 * @param \Drupal\Core\Entity\FieldableEntityInterface|null $entity
 *   (optional) The entity the field is attached to.
 * @param array $cacheable
 *   (optional) An array to add cacheability metadata to.
 *
 * @return array
 *   An associative array of allowed values, keyed by the value and with the
 *   label as the value.
 */
function oyw_salesforce_options_allowed_values(
    FieldStorageDefinitionInterface $definition,
    ?FieldableEntityInterface $entity = null,
    array &$cacheable = []
): array {
    $service = \Drupal::service('oyw_salesforce.salesforce_field_values');

    // Type hint service so I can goto the function quickly in vscode.
    assert($service instanceof SalesforceFieldValues);

    return $service->getAllowedValues($definition, $entity, $cacheable);
}
